name: CI

on:
  workflow_dispatch:
  
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Python 3.12 - Ubuntu - x64

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Use system Python
        run: python --version


      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run benchmark
        run: |
          python root_join.py --task task2 --dataset gooaq
          python eval.py results.csv

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Results
          path: |
            results.csv
